[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss18"

    [buildPlans.IosevkaCustom.variants.design]
    one = "no-base-long-top-serif"
    two = "curly-neck-serifed"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "bend-serifless"
    eight = "crossing"
    nine = "closed-contour"
    zero = "dotted"
    capital-a = "round-top-base-serifed"
    capital-b = "more-asymmetric-unilateral-serifed"
    capital-c = "serifless"
    capital-d = "standard-bilateral-serifed"
    capital-e = "serifed-capped"
    capital-f = "top-left-serifed"
    capital-g = "toothed-serifless-hookless"
    capital-h = "top-left-bottom-right-serifed"
    capital-i = "short-serifed"
    capital-j = "descending-serifed-both-sides"
    capital-l = "serifed"
    capital-m = "hanging-serifless"
    capital-p = "open-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "curly-open-top-left-serifed"
    capital-s = "unilateral-serifed"
    capital-t = "motion-serifed"
    capital-u = "tailed-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "rounded-vertical-sides-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-motion-serifed"
    capital-z = "curly-serifed-with-horizontal-crossbar"
    a = "single-storey-earless-rounded-serifless"
    b = "toothless-rounded-serifed"
    c = "serifless"
    d = "toothless-rounded-serifless"
    e = "flat-crossbar"
    f = "diagonal-tailed-crossbar-at-x-height"
    g = "double-storey-open"
    h = "tailed-serifed"
    i = "serifed-semi-tailed"
    j = "diagonal-tailed-serifed"
    k = "diagonal-tailed-cursive-serifless"
    l = "serifed-semi-tailed"
    m = "short-leg-serifless"
    n = "earless-corner-tailed-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-diagonal-tailed-serifless"
    r = "compact-serifless"
    s = "bilateral-inward-serifed"
    t = "diagonal-tailed-asymmetric-short-neck2"
    u = "toothless-rounded-motion-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "cursive"
    y = "cursive-flat-hook-serifed"
    z = "cursive-with-horizontal-crossbar"
    tittle = "round"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    guillemet = "straight"
    ampersand = "upper-open"
    at = "fourfold-tall"
    question = "smooth"
    lig-neq = "more-slanted-dotted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaCustom.variants.italic]
    one = "no-base-long-top-serif"
    two = "curly-neck-serifed"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "bend-serifless"
    eight = "crossing"
    nine = "closed-contour"
    zero = "dotted"
    capital-a = "round-top-base-serifed"
    capital-b = "more-asymmetric-unilateral-serifed"
    capital-c = "serifless"
    capital-d = "standard-bilateral-serifed"
    capital-e = "serifed-capped"
    capital-f = "top-left-serifed"
    capital-g = "toothed-serifless-hookless"
    capital-h = "top-left-bottom-right-serifed"
    capital-i = "short-serifed"
    capital-j = "descending-serifed-both-sides"
    capital-l = "serifed"
    capital-m = "hanging-serifless"
    capital-p = "open-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "curly-open-top-left-serifed"
    capital-s = "unilateral-serifed"
    capital-t = "motion-serifed"
    capital-u = "tailed-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "rounded-vertical-sides-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-motion-serifed"
    capital-z = "curly-serifed-with-horizontal-crossbar"
    a = "single-storey-earless-rounded-serifless"
    b = "toothless-rounded-serifed"
    c = "serifless"
    d = "toothless-rounded-serifless"
    e = "flat-crossbar"
    f = "diagonal-tailed-crossbar-at-x-height"
    g = "double-storey-open"
    h = "tailed-serifed"
    i = "serifed-semi-tailed"
    j = "diagonal-tailed-serifed"
    k = "diagonal-tailed-cursive-serifless"
    l = "serifed-semi-tailed"
    m = "short-leg-serifless"
    n = "earless-corner-tailed-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-diagonal-tailed-serifless"
    r = "compact-serifless"
    s = "bilateral-inward-serifed"
    t = "diagonal-tailed-asymmetric-short-neck2"
    u = "toothless-rounded-motion-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "cursive"
    y = "cursive-flat-hook-serifed"
    z = "cursive-with-horizontal-crossbar"
    tittle = "round"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    guillemet = "straight"
    ampersand = "upper-open"
    at = "fourfold-tall"
    question = "smooth"
    lig-neq = "more-slanted-dotted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaCustom.variants.oblique]
    one = "no-base-long-top-serif"
    two = "curly-neck-serifed"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "oblique-flat-serifless"
    six = "straight-bar"
    seven = "bend-serifless"
    eight = "crossing"
    nine = "closed-contour"
    zero = "dotted"
    capital-a = "round-top-base-serifed"
    capital-b = "more-asymmetric-unilateral-serifed"
    capital-c = "serifless"
    capital-d = "standard-bilateral-serifed"
    capital-e = "serifed-capped"
    capital-f = "top-left-serifed"
    capital-g = "toothed-serifless-hookless"
    capital-h = "top-left-bottom-right-serifed"
    capital-i = "short-serifed"
    capital-j = "descending-serifed-both-sides"
    capital-l = "serifed"
    capital-m = "hanging-serifless"
    capital-p = "open-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "curly-open-top-left-serifed"
    capital-s = "unilateral-serifed"
    capital-t = "motion-serifed"
    capital-u = "tailed-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "rounded-vertical-sides-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-motion-serifed"
    capital-z = "curly-serifed-with-horizontal-crossbar"
    a = "single-storey-earless-rounded-serifless"
    b = "toothless-rounded-serifed"
    c = "serifless"
    d = "toothless-rounded-serifless"
    e = "flat-crossbar"
    f = "diagonal-tailed-crossbar-at-x-height"
    g = "double-storey-open"
    h = "tailed-serifed"
    i = "serifed-semi-tailed"
    j = "diagonal-tailed-serifed"
    k = "diagonal-tailed-cursive-serifless"
    l = "serifed-semi-tailed"
    m = "short-leg-serifless"
    n = "earless-corner-tailed-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-diagonal-tailed-serifless"
    r = "compact-serifless"
    s = "bilateral-inward-serifed"
    t = "diagonal-tailed-asymmetric-short-neck2"
    u = "toothless-rounded-motion-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "cursive"
    y = "cursive-flat-hook-serifed"
    z = "cursive-with-horizontal-crossbar"
    tittle = "round"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    guillemet = "straight"
    ampersand = "upper-open"
    at = "fourfold-tall"
    question = "smooth"
    lig-neq = "more-slanted-dotted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCustom.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCustom.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.IosevkaCustom.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"
